url: "https://daveiano.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/weather-data-center" # the subpath of your site, e.g. /blog
title: "Weather data center Docs" # the name of your site, e.g. ACME Corp.
incremental: true
postcss:
  cache: false
sass:
  style: compressed
  implementation: sass-embedded
  load_paths:
    - node_modules
plugins:
  - jekyll-postcss
include: ["node_modules/tailwindcss"]
exclude: []