# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
# gem "github-pages", "~> 219", group: :jekyll_plugins
gem "jekyll-postcss"

group :jekyll_plugins do
  gem 'jekyll-sass-converter', github: 'jekyll/jekyll-sass-converter'
  gem 'sass-embedded'
end