#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

./node_modules/.bin/electron-forge package && rm -rf ./out/
#yarn run test:u
yarn run lint
yarn run test

git add *__image_snapshots__*
git add *__snapshots__*