#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @todo electron-forge not found
./node_modules/.bin/electron-forge package && rm -rf ./out/
yarn run test:u
yarn run test

git add *__image_snapshots__*
git add *__snapshots__*