# @see https://medium.com/swlh/jest-and-github-actions-eaf3eaf2427d for multi-env tests.
# @see https://joelhooks.com/jest-and-github-actions for better error reporting.
name: End-to-end tests

on:
  push:
    paths:
      - "src/**"
    branches: [1.x]
  pull_request:
    branches: [1.x]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🔨 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: 🔨 install yarn and dependecies
        run: |
          npm install -g yarn
          yarn install
      - run: npx playwright install-deps
      - name: yarn test:e2e:ci
        run: yarn test:e2e:ci
        env:
          # This might depend on your test-runner/language binding
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: 🔨 Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
